site_name: o11y.love
site_url: https://o11y.love
site_description: Learn Observability - tools, resources, newsletters, workshops, and much more. Everyone can contribute! 
site_author: Michael Friedrich
copyright: 'CC BY-SA 4.0; <a href="/privacy">Privacy Policy</a>'

# Show repository marker in the upper right corner 
repo_name: o11y.love
r