site_name: o11y.love
site_url: https://o11y.love
site_description: Learn Observability - tools, resources, newsletters, workshops, and much more. Everyone can contribute! 
site_author: Michael Friedrich
copyright: 'CC BY-SA 4.0; <a href="/privacy">Privacy Policy</a>'

# Show repository marker in the upper right corner 
repo_name: o11y.love
repo_url: https://gitlab.com/everyonecancontribute/observability/o11y.love

# main branch
edit_uri: blob/main/docs/

theme:
  name: material
  language: en 
  font:
    code: Roboto Mono  
    text: Roboto # required for social cards 
  icon:
    logo: material/heart-pulse
  favicon: assets/images/heart-pulse.svg   

  features:
    - tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top

  # Support dark/light themes 
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

# Extras 
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js  

extra:
  analytics:
    provider: google
    property: G-195X848VEY
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our newsletter and whether users
      find what they're searching for. Wi